#!env bash
# vim: foldmethod=marker 
hc() { echo HC: "$*"; herbstclient "$@"; }
# hc() { echo HC: "$*"; /home/dsf/src/WM/herbstluftwm/tmp-2018-07-03_17:17:39-BUILD/bin/herbstclient "$@"; }
# Reset configuration {{{
hc_bin=$HOME/.dotfiles/bin/herbstluftwm
hc emit_hook reload
hc keyunbind --all
hc unrule -F
# }}}
# External autostart {{{
# TODO: Make indeed external
$hc_bin/alt-tab.sh &
shutter &
# parcellite &
copyq &
dunst &
xautolock -time 8 -corners '--++' -cornerdelay 1 -cornerredelay 60 -locker 'i3lock-wrapper.sh -b' -detectsleep &
# -notify -notifier 'notify-send Locking soon...' &
# TODO: Build .xmodmap
xset -b -c r rate 200 140 dpms 0 0 3600 s off 
setxkbmap -layout us,de -option grp:alt_caps_toggle
xmodmap -e 'keycode 94 = asciitilde asciitilde asciitilde asciitilde'
# }}}
# Aliases {{{
SUPER=Mod4
ALT=Mod1
CTRL=Control
TERMINAL=${TERMINAL:-xfce4-terminal} 
BROWSER=${BROWSER:-sensible-browser} 
# }}}
# Setup basic tags {{{
tag_names=(log root coms mail )
for tag_index in {0..9}; do
	hc keybind "$SUPER-$ALT-$tag_index" use_index "$tag_index"
	hc keybind "$SUPER-$ALT-Shift-$tag_index" move_index "$tag_index"
	tag_name="${tag_names[$tag_index]}"
	[ -n "$tag_name" ] && hc add "$tag_name"
done
# }}}
# Keybindings for rofi {{{
hc keybind $SUPER+Tab spawn rofi -show window -window-format '{w}{t}{n}{r}{c}' 
hc keybind $SUPER+Tab spawn rofi -theme theme -show window -monitor -1 -width 95 -lines 40 -window-format '[{w}] {t} | n={n} | r={r} | c={c}' 
hc keybind $ALT+space spawn rofi -theme theme -fullscreen -show combi
hc keybind $ALT+$CTRL+Shift+s spawn /home/dsf/.dotfiles/bin/rofimoji.py
hc keybind F5 spawn $hc_bin/dlf.sh
hc keybind F6 spawn pactl set-sink-volume $(pactl info | sed -n 's/Default Sink: \(.*\)/\1/p') -10%
hc keybind F7 spawn pactl set-sink-volume $(pactl info | sed -n 's/Default Sink: \(.*\)/\1/p') +10%
hc keybind F8 spawn pactl set-sink-mute $(pactl info | sed -n 's/Default Sink: \(.*\)/\1/p') toggle
# }}}
# Miscellaneous keybindings {{{
hc keybind $SUPER-q close
hc keybind $ALT-F4 close
# hc keybind $SUPER-Shift-q close_and_remove
# hc keybind $SUPER-Shift-q close_or_remove
hc keybind $SUPER-r remove
# hc keybind $SUPER-Shift-r reload
hc keybind $SUPER-Return spawn $TERMINAL -x zsh -ic tmm
hc keybind $SUPER-Shift-Return spawn $TERMINAL
hc keybind $CTRL-Return spawn $BROWSER
hc keybind $SUPER-a spawn $hc_bin/i3lock-wrapper.sh
hc keybind $SUPER-Shift-a spawn xset dpms 0 0 5
hc keybind $SUPER-l chain X fullscreen false X focus right
# }}}
# Keybindings for moving clients {{{
hc keybind $SUPER-$CTRL-h shift left
hc keybind $SUPER-$CTRL-j shift down
hc keybind $SUPER-$CTRL-k shift up
hc keybind $SUPER-$CTRL-l shift right
hc keybind $SUPER-Shift-1 chain I move_index -1 I use_index -1
hc keybind $SUPER-Shift-2 chain I move_index +1 I use_index +1
hc keybind $SUPER-bracketleft chain I lock I shift_to_monitor -1 I cycle_monitor -1 I unlock
hc keybind $SUPER-bracketright chain I lock I shift_to_monitor +1 I cycle_monitor +1 I unlock
# }}}
# Keybindings for splitting frames {{{
hc keybind $SUPER-6 split explode
hc keybind $SUPER-7 chain I split right 0.5 I focus right 
# hc keybind $SUPER-7 chain I split right 0.5 I focus right I spawn $TERMINAL
hc keybind $SUPER-8 chain I split bottom 0.5
# TODO: 'focus bottom' does not work. Fix it.
# hc keybind $SUPER-8 chain I split bottom 0.8 I focus bottom
# hc keybind $SUPER-8 chain I split bottom 0.5 I focus bottom I spawn $TERMINAL
# }}}
# Keybindings for resizing frames {{{
resizestep=0.05
hc keybind $SUPER-Shift-h resize left +$resizestep
hc keybind $SUPER-Shift-j resize down +$resizestep
hc keybind $SUPER-Shift-k resize up +$resizestep
hc keybind $SUPER-Shift-l resize right +$resizestep
# }}}
# Keybindings to cycle through tags {{{
hc keybind $SUPER-1 use_index -1 --skip-visible
hc keybind $SUPER-comma use_index -1 --skip-visible
# hc keybind $SUPER-1 use_index -1 
# hc keybind $SUPER-comma use_index -1 
hc keybind $SUPER-2 use_index +1 --skip-visible
hc keybind $SUPER-period use_index +1 --skip-visible
# hc keybind $SUPER-2 use_index +1 
# hc keybind $SUPER-period use_index +1 
hc keybind $SUPER-3 use_previous
# TODO: Think about how FO could help here...
hc keybind $SUPER-9 and AND or OR compare tags.focus.name = coms OR chain FALSE use coms FALSE false AND use_previous AND
hc keybind $SUPER-0 and AND or OR compare tags.focus.name = log OR chain FALSE use log FALSE false AND use_previous AND
hc keybind $SUPER-Shift-0 spawn $hc_bin/clear_empty_tags.sh
# }}}
# Keybindings to change layout {{{
hc keybind $SUPER-s floating toggle
hc keybind $SUPER-p pseudotile toggle
hc keybind $SUPER-space spawn $hc_bin/windowmenu.sh
hc keybind $SUPER-$ALT-space spawn $hc_bin/handle_tag.sh
hc keybind $SUPER-$ALT-$CTRL-space chain X add TMP X move TMP X use TMP X spawn $hc_bin/handle_tag.sh
hc keybind $SUPER-$ALT-$CTRL-j spawn lux -s 10%
hc keybind $SUPER-$ALT-$CTRL-k spawn lux -a 10%
hc keybind $SUPER-$ALT-$CTRL-Shift-j spawn lux -S 1%
hc keybind $SUPER-$ALT-$CTRL-Shift-k spawn lux -S 100%
hc keybind $SUPER-z chain X fullscreen false X spawn $hc_bin/maximize.sh
hc keybind $SUPER-f chain X fullscreen false X spawn $hc_bin/maximize.sh
hc keybind $SUPER-Shift-z fullscreen toggle
hc keybind $SUPER-Shift-f fullscreen toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $SUPER-e or , and . compare tags.focus.curframe_wcount = 2 . cycle_layout +1 vertical horizontal max , cycle_layout +1 
hc keybind $SUPER-Shift-e or , and . compare tags.focus.curframe_wcount = 2 . cycle_layout -1 vertical horizontal max , cycle_layout -1 
# hc keybind $SUPER-e cycle_layout
# }}}
# Keybindings to change focus {{{
hc keybind $SUPER-BackSpace cycle_monitor +1
hc keybind $SUPER-Shift-BackSpace cycle_monitor -1
hc keybind $SUPER-c cycle_all +1
hc keybind $SUPER-Shift-c cycle_all -1
hc keybind $SUPER-i jumpto urgent
hc keybind $ALT+Shift+1 spawn sh -c "$hc_bin/jumpto.sh chrome"
hc keybind $ALT+Shift+2 spawn sh -c "$hc_bin/jumpto.sh thunderbird"
hc keybind $ALT+Shift+3 spawn sh -c "$hc_bin/jumpto.sh ${TERMINAL:-xfce4-terminal}"
hc keybind $SUPER-n chain X add NEW X use NEW X spawn ${BROWSER:-google-chrome-stable} X
# TODO: Not only fullscreen false but unmaximize.sh
hc keybind $SUPER-h chain X fullscreen false X focus left
hc keybind $SUPER-j chain X fullscreen false X focus down
hc keybind $SUPER-k chain X fullscreen false X focus up
hc keybind $SUPER-l chain X fullscreen false X focus right
# }}}
# Mouse bindings {{{
hc mouseunbind --all
hc mousebind $SUPER-Button1 move
hc mousebind $SUPER-Button2 zoom
hc mousebind $SUPER-Button3 resize
hc mousebind Mod1-B4 call substitute WID clients.dragged.winid spawn transset --inc -i WID 0.05
hc mousebind Mod1-B5 call substitute WID clients.dragged.winid spawn transset --dec -i WID -m 0.2
hc set focus_follows_mouse 1
# }}}
# Colorthema {{{
xsetroot -solid '#000000'
# x3setroot -solid '#5A8E3A'
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#222222'
hc set frame_border_normal_color '#101010'
hc set frame_bg_normal_color '#565656'
hc set frame_bg_active_color '#345F0C'
hc set frame_border_width 1
hc set always_show_frame 1
hc set frame_bg_transparent 1
hc set frame_transparent_width 5
hc set frame_gap 0

# hc attr theme.active.color '#9fbc00'
hc attr theme.active.color '#aa0000'
hc attr theme.normal.color '#454545'
hc attr theme.urgent.color orange
hc attr theme.inner_width 1
hc attr theme.inner_color black
hc attr theme.border_width 3
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#3E4A00'
# hc attr theme.active.outer_color '#3E4A00'
hc attr theme.active.outer_color '#ffffff'
hc attr theme.background_color '#141414'
# }}}
# Settings {{{
hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0
hc set auto_detect_monitors 1
hc set focus_stealing_prevention 0
hc set swap_monitors_to_get_tag 1
hc set raise_on_focus 0
# hc set tree_style '╾│ ├└╼─┐'
hc set tree_style '╾│ ├╰╼─╮'
# }}}
# Rules {{{
hc rule focus=on 
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

# Tag: coms
hc rule instance=crx_nckgahadagoaajjgafhacjanaoiihapd tag=coms focus=true
hc rule title="Telegram Web - Google Chrome" tag=coms

# Tag: mail
hc load mail '(split horizontal:0.850000:0 (clients horizontal:0 0x3600010) (clients horizontal:0 0x3600047))'
hc rule class=Thunderbird tag=mail index=0
hc rule class=Thunderbird title~"Reminder[s]*" tag=mail index=1
hc rule class=Thunderbird focus=false

# }}}
# Setup panels {{{
panel=~/.config/herbstluftwm/panel.sh
if [ -x "$panel" ]; then
	for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
		# start it on each monitor
		"$panel" $monitor &
	done
fi
# }}}

hc unlock
hc detect_monitors
