#!/usr/bin/env bash
set -x

hc() {
    herbstclient "$@"
}
hc_bin=$HOME/.dotfiles/bin/herbstluftwm

hc emit_hook reload

# x3setroot -solid '#5A8E3A'
xsetroot -solid '#000000'
xset -b -c r rate 200 140
shutter &
parcellite &
dunst &
xautolock -time 9 -corners '--++' -cornerdelay 1 -cornerredelay 60 -locker i3lock-wrapper.sh -detectsleep &

# remove all existing keybindings
hc keyunbind --all

# keybindings
SUPER=Mod4
ALT=Mod1
CTRL=Control

# rofi
hc keybind $SUPER+Tab spawn rofi -show window -window-format '{w}{t}{n}{r}{c}' 
hc keybind $SUPER+Tab spawn rofi -theme theme -show window -monitor -1 -width 95 -lines 40 -window-format '[{w}] {t} | n={n} | r={r} | c={c}' 
hc keybind $ALT+space spawn rofi -theme theme -fullscreen -show combi
hc keybind $ALT+$CTRL+Shift+s spawn python ~/.dotfiles/bin/rofimoji.py

# TODO: make frame disappear after last windows 
hc keybind $SUPER-Shift-q close
hc keybind $SUPER-Shift-r reload
hc keybind $SUPER-Return spawn ${TERMINAL:-xfce4-terminal} # use your $TERMINAL with xterm as fallback

# basic movement
# focusing clients
# TODO: Not only fullscreen false but unmaximize.sh
hc keybind $SUPER-h chain X fullscreen false X focus left
hc keybind $SUPER-j chain X fullscreen false X focus down
hc keybind $SUPER-k chain X fullscreen false X focus up
hc keybind $SUPER-l chain X fullscreen false X focus right

# moving clients
hc keybind $SUPER-Shift-h shift left
hc keybind $SUPER-Shift-j shift down
hc keybind $SUPER-Shift-k shift up
hc keybind $SUPER-Shift-l shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $SUPER-u split   bottom  0.5
hc keybind $SUPER-o split   right   0.5
# let the current frame explode into subframes
hc keybind $SUPER-Control-space split explode

# resizing frames
resizestep=0.05
hc keybind $SUPER-Shift-h resize left +$resizestep
hc keybind $SUPER-Shift-j resize down +$resizestep
hc keybind $SUPER-Shift-k resize up +$resizestep
hc keybind $SUPER-Shift-l resize right +$resizestep

# tags
tag_names=(log mail coms root)
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$SUPER-$key" use_index "$i"
        hc keybind "$SUPER-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $SUPER-1 use_index -1 --skip-visible
hc keybind $SUPER-comma use_index -1 --skip-visible
# hc keybind $SUPER-1 use_index -1 
hc keybind $SUPER-2 use_index +1 --skip-visible
hc keybind $SUPER-period use_index +1 --skip-visible
# hc keybind $SUPER-2 use_index +1 
hc keybind $SUPER-3 use_previous
# TODO: Think about how FO could help here...
hc keybind $SUPER+9 and AND or OR compare tags.focus.name = coms OR chain FALSE use coms FALSE false AND use_previous AND
hc keybind $SUPER+0 and AND or OR compare tags.focus.name = log OR chain FALSE use log FALSE false AND use_previous AND

hc keybind $SUPER-n chain X add NEW X use NEW X spawn ${BROWSER:-google-chrome-stable} X

# layouting
hc keybind $SUPER-r remove
hc keybind $SUPER-s floating toggle
hc keybind $SUPER-space spawn sh -c $hc_bin/windowmenu.sh
hc keybind $SUPER-z chain X fullscreen false X spawn sh -c $hc_bin/maximize.sh
hc keybind $SUPER-f chain X fullscreen false X spawn sh -c $hc_bin/maximize.sh X
hc keybind $SUPER-Shift-f fullscreen toggle
hc keybind $SUPER-p pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $SUPER-t                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $SUPER-Button1 move
hc mousebind $SUPER-Button2 zoom
hc mousebind $CTRL-$SUPER-$ALT-Button2 call close-or-remove
hc mousebind $SUPER-Button3 resize
hc mousebind Mod1-B4 call substitute WID clients.dragged.winid spawn transset --inc -i WID 0.05
hc mousebind Mod1-B5 call substitute WID clients.dragged.winid spawn transset --dec -i WID -m 0.2
hc set focus_follows_mouse 1

# focus
hc keybind $SUPER-BackSpace   cycle_monitor
# hc keybind $SUPER-Tab         cycle_all +1
# hc keybind $SUPER-Shift-Tab   cycle_all -1
hc keybind $SUPER-c cycle
hc keybind $SUPER-i jumpto urgent
hc keybind $ALT+Shift+1 spawn sh -c "$hc_bin/jumpto.sh chrome"
hc keybind $ALT+Shift+2 spawn sh -c "$hc_bin/jumpto.sh thunderbird"
hc keybind $ALT+Shift+3 spawn sh -c "$hc_bin/jumpto.sh ${TERMINAL:-xfce4-terminal}"

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#222222'
hc set frame_border_normal_color '#101010'
hc set frame_bg_normal_color '#565656'
hc set frame_bg_active_color '#345F0C'
hc set frame_border_width 1
hc set always_show_frame 1
hc set frame_bg_transparent 1
hc set frame_transparent_width 5
hc set frame_gap 4

hc attr theme.active.color '#9fbc00'
hc attr theme.normal.color '#454545'
hc attr theme.urgent.color orange
hc attr theme.inner_width 1
hc attr theme.inner_color black
hc attr theme.border_width 3
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#3E4A00'
hc attr theme.active.outer_color '#3E4A00'
hc attr theme.background_color '#141414'

hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0
hc set auto_detect_monitors 1
hc set swap_monitors_to_get_tag 1
hc set raise_on_focus 0
# hc set tree_style '╾│ ├└╼─┐'
hc set tree_style '╾│ ├╰╼─╮'

# rules
hc unrule -F
hc rule focus=on 
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

hc rule instance=crx_nckgahadagoaajjgafhacjanaoiihapd tag=coms focus=on
hc rule title="Telegram Web - Google Chrome" tag=coms
hc rule class=Thunderbird tag=mail

# unlock, just to be sure
hc unlock

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
hc detect_monitors

# find the panel
panel=~/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    "$panel" $monitor &
done
$hc_bin/alt-tab.sh&
